version: "1.0"
workspace:
  parent_page_id: "251b90822b5981ff9c43de21f0533607"

databases:
  - db_key: customers
    title: "Customers"
    properties:
      Name: { type: title }
      Email: { type: email }
